site_name: LearnD3D11
site_author: deccer
site_url: https://graphicsprogramming.github.io/learnd3d11
repo_name: graphicsprogramming/learnd3d11
repo_url: https://github.com/graphicsprogramming/learnd3d11
site_description: Learn D3D11
copyright: Copyright 2022 Graphics Programming
theme:
  name: material
  logo: https://cdn.discordapp.com/attachments/908076591547052032/937089306009432084/unknown.png
  palette:
    - scheme: default
      primary: light-green
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    code: Roboto Mono
  language: en
  features:
    - tabs
    - instant
plugins:
  - search
  - mkdocs-nav-enhancements
  - literate-nav:
      nav_file: nav.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/graphicsprogramming/learnd3d11
      name: Graphics Programming on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6mgNGk7
      name: Graphics Programming on discord
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - markdown.extensions.toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
nav:
- Introduction: 1-introduction/1-0-overview.md
- Getting Started:
    - 1-introduction/1-1-getting-started/1-1-0-overview.md
    - 1-introduction/1-1-getting-started/1-1-1-what-is-dx11.md
    - 1-introduction/1-1-getting-started/1-1-2-hello-window.md
    - 1-introduction/1-1-getting-started/1-1-3-hello-d3d11.md
    - 1-introduction/1-1-getting-started/1-1-4-hello-triangle.md
- Debugging:
    - 1-introduction/1-2-debug/1-2-0-overview.md
    - 1-introduction/1-2-debug/1-2-1-clear-state.md
    - 1-introduction/1-2-debug/1-2-2-debug-layer.md
    - 1-introduction/1-2-debug/1-2-3-naming-things.md
    - 1-introduction/1-2-debug/1-2-4-renderdoc.md
    - 1-introduction/1-2-debug/1-2-5-laptop-gpus.md
- Models:
    - 1-introduction/1-3-models/1-3-0-overview.md
    - 1-introduction/1-3-models/1-3-1-image-library.md
    - 1-introduction/1-3-models/1-3-2-loading-meshes.md
    - 1-introduction/1-3-models/1-3-3-depthstencil-texture.md
    - 1-introduction/1-3-models/1-3-4-depthstencil-state.md
    - 1-introduction/1-3-models/1-3-5-index-buffer.md
    - 1-introduction/1-3-models/1-3-6-coordinate-systems.md
    - 1-introduction/1-3-models/1-3-7-constant-buffer.md
    - 1-introduction/1-3-models/1-3-8-camera.md
- Code:
    - 8-code/repository.md
- License: license.md
- About: about.md